config/routes.rb
Gdae::Application.routes.draw do
  devise_for :users
  get "ssl/index"
  get "ssl/about"
  get "ssl/admin"
  get "ssl/search"
  get "ssl/users"
  root "ssl#index"

  get '/ssl/promote_user/:promote_id', to: 'ssl#promote_user', as: 'promote'
  get '/find', to: 'doc#find', as: 'result'
  get '/doc/:id', to: 'doc#show', as: 'doc'
  get '/raw/:id', to: 'doc#raw', as: 'raw'
  get '/delete/:id', to: 'doc#delete', as: 'delete'
  get '/edit/:id', to: 'doc#edit', as: 'edit'
  get '/doc', to: 'doc#index', as: 'docs'
  post '/doc/create', to: 'doc#create'
  post '/doc/update', to: 'doc#update'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doc_controller.rb
require 'jsonclient'
require 'mongo'
include Mongo
require 'uri'

class DocController < ApplicationController
	def index
		@cursor = ssl.find(filters).sort(sorted_by)
		@docs = []
		start = params[:page].to_i * 20 
		@cursor.skip(start).first(21).each do |d|
			@docs << d
		end
		@dpag = Kaminari.paginate_array(@docs).page(1).per(20)
	end

	def show
		@doc = ssl.find({id: params[:id]}).to_a.first
		if @doc.nil?
			redirect_to docs_path, notice: 'No record of doc with id: ' + params[:id].to_s  
		end
	end

	def raw
		@raw = ssl.find({id: params[:id]}).to_a.first
		if @raw.nil?
			redirect_to doc_index_path, notice: 'No record of doc with id: ' + params[:id].to_s  
    else
    	render json: @raw 
		end
  end

	def find
		clnt = JSONClient.new
		header = {'Cookie' => 'Summon-Two=true'}
		uri = URI.parse(URI.encode("http://tufts.summon.serialssolutions.com/api/search?pn=1&ho=t&q=" + params[:title]))
		response = clnt.get(uri, nil, header)
		json_response = response.content
		if json_response.keys.include?("documents")
			@result = response.content["documents"]
		else
			@result = ''
		end
	end

	def create
		if params[:new_doc_contents].nil?
			puts 'Failed to find new_doc_contents'
			redirect_to doc_find_path, alert: 'Could not find that doc'
		else
			new_doc = params[:new_doc_contents]
			new_doc['title'] = new_doc['title'].gsub('<b>', '').gsub('</b>', '').titleize
			if new_doc['isbn'].nil?
				if new_doc['eissns'].nil?
					if not new_doc['issns'].nil? and not new_doc['issns'].split('"')[1].nil?
						new_doc['id'] = new_doc['issns'].split('"')[1]
					end
				else
					if not new_doc['eissns'].nil? and not new_doc['eissns'].split('"')[1].nil?
						new_doc['id'] = new_doc['eissns']
					end
				end
			else
				new_doc['id'] = new_doc['isbn']
			end
			begin
			 	new_id = ssl.insert(new_doc)
			 	new_doc_id = new_doc['id']
				redirect_to doc_path(new_doc_id), notice: 'Your document was successfully added to the SSL'
			rescue Mongo::OperationFailure => e
				redirect_to ssl_admin_path, alert: 'Error inserting document: ' + e.message
			end
		end
	end

  def edit
    if current_user.try(:admin?)
      @edit = ssl.find({id: params[:id]}).to_a.first
      if @edit.nil?
        redirect_to doc_index_path, alert: 'No record of doc with id: ' + params[:id].to_s  
      end
    else
    	redirect_to root_path, alert: 'You do not have permission to edit SSL entries'
  	end
  end

  def update
    if current_user.try(:admin?)
      old_entry = ssl.find({id: params[:id]}).to_a.first
      mongo_id = params["_id"]
      update_mongo_id = old_entry["_id"]
      if mongo_id.nil?
        puts 'Failed to find id'
        redirect_to docs_path, alert: 'Could not edit that doc'
      else
        begin
          params.to_json
        rescue JSON::JsonError
          puts 'JSON Error'
          redirect_to doc_path(params[:id]), alert: 'Your edits were not successful. Please try again.'
        end
        updated_keys = {}
        params.each do |key, value|
          if key != "_id" and old_entry.include?(key) and value != old_entry[key]
            # don't want to try to update fields with the same value--mongo doesn't seem to like that
            updated_keys[key] = value
          end
        end
        # ssl.update never succeeds and I have no clue why
        status = ssl.update({"_id" => update_mongo_id}, {"$set" => updated_keys}, {"$upsert" => true})
        if status[:ok] == 0 or status[:nModified] == 0
          puts updated_keys
          puts 'Status error: ' + status.to_s
          redirect_to doc_path(params[:id]), alert: 'Your edits were not successful. Please try again.'
        else
          redirect_to doc_path(params[:id]), notice: 'Your document was successfully edited'
        end
      end	
    else
      redirect_to root_path, alert: 'You do not have permission to edit SSL entries'
    end
  end

  def delete
	  if current_user.try(:admin?)
      puts params
      if params[:id].nil?
        puts 'Failed to find id'
        redirect_to doc_index_path, notice: 'Could not delete that doc'
      else
        ssl.remove({id: params[:id]})
        redirect_to docs_path, notice: 'Your document was successfully deleted from the SSL'
      end
	  else
      redirect_to root_path, alert: 'You do not have permission to delete entries from the SSL'
	  end
  end

	private
		def ssl
			mongo_uri = ENV['SSL_MONGODB']
			db_name = mongo_uri[%r{/([^/\?]+)(\?|$)}, 1]
			client = MongoClient.from_uri(mongo_uri)
			db = client.db(db_name)
			db.collection('ssl')
		end

		def filters
			flts = {}
			if params.has_key?(:title) and params[:title].match(/^[[:alnum:]\ ]+$/)
				title = Regexp.new(params[:title].split(' ').map{|word| '(?=.*' << word << ')'}.join(''), true)
				flts["title"] = title
			end
			if params.has_key?(:author) and params[:author].match(/^[[:alnum:]\ ]+$/)
				flts["author"] = Regexp.union(params[:author].split(' ').map{|w| Regexp.new(w, true)})
			end
			if params.has_key?(:keywords) and params[:keywords].match(/^[[:alnum:]\ ]+$/)
				keywords = Regexp.union(params[:keywords].split(' ').map{|word| Regexp.new(word, true)})
				flts["subject_terms"] = keywords
			end
			if params.has_key?(:disciplines) and params[:disciplines].match(/^[[:alnum:]\ ]+$/)
				flts["disciplines"] = Regexp.union(params[:disciplines].split(' ').map{|word| Regexp.new(word, true)})
			end
			if params.has_key?(:publisher) and params[:publisher].match(/^[[:alnum:]\ ]+$/)
				flts["publisher"] = Regexp.new(params[:publisher], true)
			end
			if params.has_key?(:isbn) and not params[:isbn].nil?
				flts["isbn"] = Regexp.new(Regexp.escape(params[:isbn]), true)
			end
			flts
		end

		def sorted_by
			srt = {}
			if params.has_key?(:sort_by) and params[:sort_by].match(/^[[:alnum:]\ ]+$/)
				srt[params[:sort_by]] = 1
			else
				srt[:title] = 1
			end
			srt
		end
end

app/controllers/ssl_controller.rb
class SslController < ApplicationController
  def index
  end

  def about
  end

  def admin
  end

  def search
  end

  def users
  	@users = []
  	# Show admins all users so they can promote users
  	if current_user.try(:admin?)
  		@users = User.all.order(admin: :desc, sign_in_count: :desc, email: :asc)
  	elsif user_signed_in?
  		# Only show the admins to other users, so they can request a promotion
  		@users = User.where(admin: true).order(sign_in_count: :desc, email: :asc)
  	end
  end

  def promote_user
  	if current_user.email == 'jake.schmitz101@gmail.com' or (current_user.try(:admin?) and params[:promote_id])
  		user_to_promote = User.find(params[:promote_id])
  		puts user_to_promote
  		if 
  			user_to_promote.update_attributes(admin: true)
  			redirect_to root_path, notice: 'User was promoted to admin status.'
  		else
  			redirect_to root_path, alert: 'User was already an admin!'
  		end
  	else
  		redirect_to root_path, alert: 'You do not have permission to promote that user'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doc_helper.rb
module DocHelper
end

app/helpers/ssl_helper.rb
module SslHelper
end

app/views/doc/_doc.html.erb
<% if not doc['title'].nil? %>
	<h3><%= doc['title'].html_safe %></h3>
		<h4>Author(s):  <% if not doc['authors'].nil?  
						then authors = eval(doc['authors'].to_s.gsub(':', '=>').gsub('u\'', '\'')).map{|x| x['fullname'] }.join('; ')
					else authors = doc['authors'] end %>
			<%= authors.html_safe %>
		</h4>

	<div class="panel panel-info">
		<div class="panel-heading">
			<div class="panel-title">About this Entry</div>
		</div>
		<div class="panel-body" style="overflow-x: scroll">
			<table class="table">
					<% if not doc['abstracts'].nil? %>
					<tr>
						<th>Abstract</th>
						<% if doc['abstracts'].class == String
									then abstracts = eval(doc['abstracts'].gsub(':', '=>').gsub('u\'', '\'').gsub('u"', '"')).each{|x| x.to_s }
									else abstracts = doc['abstracts'] end %>
						<td><% if not abstracts[0].nil? %>
								<% s = abstracts[0]['abstract'].gsub('=>', ':') %>
								<% if ! s.valid_encoding?
  s = s.encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')
end %>
								<%= s.to_s %>
							<% end %>
						</td>
					</tr>
					<% end %>
					<% if not doc['publication_title'].nil? %>
					<tr>
						<th>Publication Title</th>
						<td><%= doc['publication_title'] %></td>
					</tr>
					<% end %>
					<% if not doc['publisher'].nil? %>
					<tr>
						<th>Publisher</th>
						<td><%= doc['publisher'] %></td>
					</tr>
					<% end %>
					<% if not doc['publication_date'].nil? %>
					<tr>
						<th>Publication Date</th>
						<td><%= doc['publication_date'] %></td>
					</tr>
					<% end %>
					<% if not doc['uris'].nil? %>
					<tr>
						<th>URIs</th>
						<% if doc['uris'].class == String
								then uris = eval(doc['uris'].gsub('u\'', '\'').gsub('u"', '"'))
								else uris = doc['uris'] end %>
						<% uris = uris.each{|x| x.replace('<a href="' + x.to_s + '" target="_blank">' + x.to_s + '</a>') }.join('<br />') %>
						<td><%= uris.html_safe %></td>
					</tr>
					<% end %>
					<% if not doc['subject_terms'].nil? %>
			<tr>
			<th>Keywords</th>
						<td><%= eval(doc['subject_terms'].to_s.encode("UTF-8", invalid: :replace, undef: :replace).gsub('u\'', '\'').gsub('u"', '"').gsub(/\\.e./, 'e')).sort.join('<br />').html_safe %></td>
			</tr>
			<% end %>
					
				</table>
			</div>
		</div>
<% else %>
	<p>Unable to find results for <%= doc.to_s %></p>
<% end %>

app/views/doc/_doc_row.html.erb
<tr class="doc">
  <td><a href=<%= doc_path(id: doc['id']) %>><%= if not doc['full_title'].nil? then doc['full_title'].html_safe else doc['title'].html_safe end %></a></td>
      <% if doc['authors'].class == String
             then authors = eval(doc['authors'].gsub('u\'', '\'').gsub(':', '=>')) 
      else authors = doc['authors'] end %>
  <td>
    <% if not authors.nil? and not authors[0].nil? and not authors[0]['fullname'].nil?%>
      <%= authors[0]['fullname'] %>
    <% elsif not authors[0].nil? %>
      <%= authors[0]['fullname'] %>
    <% end %>
  </td>
  <td><%= doc['isbn'] %></td>
</tr>

app/views/doc/_doc_table_body.html.erb
<% @dpag.each do |d| %>
  <% doc = d %>
  <tr class="doc">
    <td><a href=<%= doc_path(id: doc['id']) %>><%= if not doc['full_title'].nil? then doc['full_title'].html_safe else doc['title'].html_safe end %></a></td>
        <% if doc['authors'].class == String
               then authors = eval(doc['authors'].gsub('u\'', '\'').gsub(':', '=>')) 
        else authors = doc['authors'] end %>
    <td>
      <% if not authors.nil? and not authors[0].nil? and not authors[0]['fullname'].nil?%>
        <%= authors[0]['fullname'] %>
      <% elsif not authors[0].nil? %>
        <%= authors[0]['fullname'] %>
      <% end %>
    </td>
    <td><%= doc['isbn'] %></td>
  </tr>
<% end %>

app/views/doc/edit.html.erb
<% if not @edit['title'].nil? %>
    <h3><%= @edit['title'].html_safe %></h3>
    <h4>Author(s):  <% if not @edit['authors'].nil?  
			    then authors = eval(@edit['authors'].to_s.gsub(':', '=>').gsub('u\'', '\'')).map{|x| x['fullname'] }.join('; ')
			    else authors = @edit['authors'] end %>
	<%= authors.html_safe %></h4>
<% end %>

<div class="panel panel-info">
    <div class="panel-heading">
        <div class="panel-title">Modify this Entry</div>
    </div>
</div>
<div class="panel-body" style="overflow-x: scroll">
    <%= form_tag(doc_update_path) do |f| %>
        <table class="table">
            <% @edit.each do |k, v| %>
                <tr>
                    <td><%= label_tag(k, k) %></td>
                    <td><%= text_field_tag(k, v, size: "100%") %></td>
                </tr>
            <% end %>
        </table>
        <%= submit_tag("Submit Changes", class: 'btn btn-primary') %>
    <% end %>
</div>

app/views/doc/find.html.erb
<% if not @result.nil? and not @result.empty? %> 
    <h3 style="display: inline-block;">Is this the article you wanted?</h3>
    <div class="btn-group" role="group" style="margin-bottom: 10px">
        <button type="button" class="btn" id="btn-no">Next</button>
    </div>
    <ul id="results">
    <% @result.each do |r| %>
        <% r["id"] =  if r["isbn"].nil? then r["id"] else r["isbn"] end %>
        <li style="list-style-type: none">
            <%= form_tag(doc_create_path(new_doc_contents: r)) do %>
                <%= submit_tag("Correct", class: 'btn btn-primary') %>
            <% end %>
            <%= render partial: '/doc/doc', locals: { doc: r } %>
            <a class="btn btn-primary" href=<%= raw_path(id: r["id"]) %>>View Raw JSON</a>
        </li>
    <% end %>

    <script>
        var $listItems = $('#results > li');

        // hide all the list items and show the first one
        $($listItems).hide().eq(0).show();

        $('#btn-no')
            .click(function() {
                var currentItem = $($listItems) 
                                        .filter(':visible')
                                        .hide()
                                        .next();
                currentItem.show();
                if ($($listItems).filter(':visible').length == 0) {
                    $('p').replaceWith("<p>No results found.</p>");
                    $('button').remove();
                }
        });
    </script>
<% else %>
    <p>No results found.</p>
<% end %>

app/views/doc/index.html.erb
<div class="ssl-table-search">
  <%= form_tag("/doc", method: "get") do %>
    <%= label_tag(:title, "Search for title:") %>
    <%= text_field_tag(:title, params[:title])%>
    <%= label_tag(:author, "Author(s):") %>
    <%= text_field_tag(:author, params[:author]) %>
    <%= label_tag(:keywords, "Keywords:") %>
    <%= text_field_tag(:keywords, params[:keywords]) %>
    <%= submit_tag("Search", class: 'btn btn-primary') %>
    <%= link_to 'Clear', docs_path %>
  <% end %>
</div>
<div class="panel panel-info ssl-table">
  <div class="panel-heading">
    <div class="panel-title">
    <% if not (params[:title] == '' and params[:author] == '' and params[:keywords] == '') %>SSL Filters <% else %>Social Science Library<% end %> 
    <% if not params[:title].nil? and params[:title] != '' %>| Title: <%= params[:title] %> <% end %>
    <% if not params[:author].nil? and params[:author] != ''%>| Author: <%= params[:author] %> <% end %>
    <% if not params[:keywords].nil? and params[:keywords] != ''%>| Keywords: <%= params[:keywords] %> <% end %>
    </div>
  </div>
  <div class="panel-body">
    <table class="table" id="docs">
      <thead>
        <tr>
          <th><a href=<%= docs_path({sort_by: :title}) %>>Title</a></th> 
          <th><a href=<%= docs_path({sort_by: :author}) %>>Author(s)</a></th>
          <th><a href=<%= docs_path({sort_by: :isbn}) %>>ISBN</a></th>
        </tr>
      </thead>
      <tbody class="page">
        <%= render partial: '/doc/doc_table_body' %>
      </tbody>
    </table>
    <%= paginate @dpag %>
  </div>
</div>

app/views/doc/index.js.erb
$("#docs").append("<tbody class='page'><%= render partial: '/doc/doc_table_body' %></tbody>");

app/views/doc/show.html.erb
<%= render partial: '/doc/doc', locals: { doc: @doc } %>

<a class="btn btn-primary" href=<%= raw_path(id: @doc['id']) %>>View Raw JSON</a>
<% if current_user.try(:admin?) %>
    <a class="btn btn-info" href=<%= edit_path(id: @doc['id']) %>>Edit</a>
    <a class="btn btn-danger" href=<%= delete_path(id: @doc['id']) %>>Delete</a>
<% end %>

app/views/layouts/_google_analytics_snippet.html.erb
<% if Rails.env == "production"  %>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-61765250-1', 'auto');
	  ga('send', 'pageview');

	</script>
<% end %>

app/views/layouts/_ssl_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>>Social Science Library</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to("About", ssl_about_path) %></li>
        <li><%= link_to("Search", ssl_search_path) %></li>
        <li><%= link_to("Full Listing", docs_path) %></li>
        <% if current_user.try(:admin?) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href=<%= ssl_admin_path %>>Add Document</a></li>
              <li class="divider"></li>
              <li><a href=<%= ssl_users_path %>>View Users</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </p>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gdae</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-61765250-1', 'auto');
	  ga('send', 'pageview');

	</script>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render partial: '/layouts/ssl_nav' %>
	<div class="container main-container">
		<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/ssl/_ssl_search.html.erb
<div class="ssl-search" style="text-align: center">
  <h2>Search the SSL</h2>
  <%= form_tag("/doc", method: "get", style: 'display: inline-block; text-align: right;') do %>
    <h5 style="text-align: center;">Search The SSL</h5>
    <%= label_tag(:title, "Title:") %>
    <%= text_field_tag(:title, params[:title])%>
    </br>
    <%= label_tag(:author, "Author(s):") %>
    <%= text_field_tag(:author, params[:author]) %>
    </br>
    <%= label_tag(:isbn, "ISBN:") %>
    <%= text_field_tag(:isbn, params[:isbn]) %>
    </br>
    <%= label_tag(:disciplines, "Discipline(s):") %>
    <%= text_field_tag(:disciplines, params[:disciplines]) %>
    </br>
    <%= label_tag(:keywords, "Keyword(s):") %>
    <%= text_field_tag(:keywords, params[:keywords]) %>
    </br>
    <%= label_tag(:publisher, "Publisher:") %>
    <%= text_field_tag(:publisher, params[:publisher]) %>
    </br>
    <%= submit_tag("Search", class: 'btn btn-primary') %>
    <%= link_to 'Clear', docs_path %>
  <% end %>
</div>

app/views/ssl/admin.html.erb
<h1>Add an Entry</h1>

<%= form_tag("/find", method: "get") do %>
	<h5>Search By:</h5>
  <%= label_tag(:title, "Title:") %>
  <%= text_field_tag(:title, params[:title])%>
  </br>
  <%= submit_tag("Search", class: 'btn btn-primary') %>
  <%= link_to 'Clear', docs_path %>
<% end %>

app/views/ssl/index.html.erb
<div class="home-center">
  <h2>Welcome to the Social Science Library:</h2>
  <h3>Frontier Thinking in Sustainable Development and Human Well-Being</h3>

  <h4 style="font-style: italic">A project of</h4>

  <p><a href="https://ase.tufts.edu/gdae/">The Global Development And Environment Institute (GDAE)</a></p>
  <p>at Tufts University in conjunction with</p>
  <p>the UN Decade for Education for Sustainable Development.</p>
</div>
<br>
<div class="home-text">
  <p>The Social Science Library (SSL) contains complete bibliographic references for over 9,300 journal articles, book chapters, and working papers covering Anthropology, Economics, History, Political Science, Social Psychology, Sociology, and Philosophy. The complete text of about 3,200 of these documents are included in the SSL.</p>
  <%= render partial: '/ssl/ssl_search' %><br><br>
</div>

app/views/ssl/search.html.erb
<%= render partial: '/ssl/ssl_search' %>

app/views/ssl/users.html.erb
<% if user_signed_in? %>
	<div class="users">
		<div class="panel panel-info user-table">
	  	<div class="panel-heading">
	    	<div class="panel-title">
	    		Users
	    	</div>
	    </div>
	    <div class="panel-body">
	    	<table class="table">
	      	<tr>
	      		<th>Email Address</th>
	      		<th>Admin?</th>
	      		<th>Last Sign In</th>
	      		<% if current_user.try(:admin?) %><th>Actions</th><% end %>
	      	</tr>
	      	<% @users.each do |user| %>
	      		<tr class="user-row">
	      			<td><a href=<%= "mailto:" + user.email %>><%= user.email %></a></td>
	      			<td><%= user.admin ? "Yes" : "No" %></td>
	      			<td><%= user.last_sign_in_at %></td>
	      			<% if current_user.try(:admin?) %>
	      				<td>
	      					<%= link_to "Delete", 
	      							registration_path(user), 
	      							data: { confirm: "Are you sure?" }, 
	      							method: :delete, class: 'btn btn-danger' %>
	      					<% if not user.admin? %>
	      						<%= link_to "Make Admin", 
	      								promote_path(user.id), 
	      								class: 'btn btn-primary' %>
	      					<% end %>
	      				</td>
	      			<% end %>
	      		</tr>
	      	<% end %>
	      </table>
	    </div>
	  </div>
	</div>
<% else %>
	<h2>You must sign in to see other users of the SSL</h2>
	<%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-primary'  %>
  <%= link_to "Login", new_user_session_path, :class => 'btn btn-primary'  %>
<% end %>